-- ===================================================
-- SCHEMA DO BANCO DE DADOS - BOLAWIN (SUPABASE POSTGRES)
-- Cole este script no "SQL Editor" do seu painel Supabase
-- e clique em "RUN".
-- ===================================================

-- 1. Criação da Tabela de Usuários
CREATE TABLE IF NOT EXISTS public.users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    telefone TEXT UNIQUE NOT NULL,
    senha TEXT NOT NULL,
    nome TEXT DEFAULT '',
    cpf TEXT DEFAULT '',
    saldo NUMERIC(12,2) DEFAULT 0.00,
    chave_pix TEXT DEFAULT '',
    role TEXT DEFAULT 'user',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Criação da Tabela de Saques
CREATE TABLE IF NOT EXISTS public.saques (
    id TEXT PRIMARY KEY,
    user_id BIGINT REFERENCES public.users(id) ON DELETE CASCADE,
    nome TEXT,
    telefone TEXT,
    valor NUMERIC(12,2) NOT NULL,
    chave_pix TEXT,
    status TEXT DEFAULT 'pendente',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Inserção do Administrador Padrão (cesar123 / cesar123)
-- Só insere se não existir ainda
INSERT INTO public.users (telefone, senha, nome, cpf, saldo, chave_pix, role)
SELECT 'cesar123', 'cesar123', 'Diretor Cesar', '00000000000', 1000.00, '', 'admin'
WHERE NOT EXISTS (
    SELECT 1 FROM public.users WHERE telefone = 'cesar123'
);

-- 4. Desabilitar Row Level Security (RLS) para permitir acesso seguro via backend Node.js
ALTER TABLE public.users DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.saques DISABLE ROW LEVEL SECURITY;
